[General]

bypass-system = true

ipv6 = false

prefer-ipv6 = false

private-ip-answer = true

dns-direct-system = false

dns-fallback-system = false

dns-direct-fallback-proxy = true

dns-server = tls://2606:4700:4700::1112:853,tls://2606:4700:4700::1002:853,tls://1.1.1.2:853,tls://1.0.0.2:853,https://security.cloudflare-dns.com/dns-query,2606:4700:4700::1112,2606:4700:4700::1002,1.1.1.2,1.0.0.2, tls://2001:4860:4860::8888:853,tls://2001:4860:4860::8844:853,tls://8.8.8.8:853,tls://8.8.4.4:853,https://dns.google/dns-query,2001:4860:4860::8888,2001:4860:4860::8844,8.8.8.8,8.8.4.4

 Яндекс не используется в качестве основного сервера т.к. опирается на Национальную систему доменных имен (НСДИ): если Роскомнадзор удалит оттуда сайт, Яндекс должен будет подчиниться
fallback-dns-server = tls://77.88.8.88:853,https://safe.dot.dns.yandex.net/dns-query,2a02:6b8::feed:bad,77.88.8.88,system

hijack-dns = :53

skip-proxy = 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,localhost,*.local,captive.apple.com

tun-excluded-routes = 10.0.0.0/8,100.64.0.0/10,127.0.0.0/8,169.254.0.0/16,172.16.0.0/12,192.0.0.0/24,192.0.2.0/24,192.88.99.0/24,192.168.0.0/16,198.51.100.0/24,203.0.113.0/24,224.0.0.0/4,255.255.255.255/32,239.255.255.250/32

icmp-auto-reply = false

always-reject-url-rewrite = false

udp-policy-not-supported-behaviour = REJECT

include = sr_ru_extended.conf

update-url = https://cdn.jsdelivr.net/gh/misha-tgshv/shadowrocket-configuration-file@main/conf/sr_ru_basic.conf

Israel-Group = url-test, policy-regex-filter=(🇮🇱|Израиль|Israel), interval=600, timeout=5, url=http://www.gstatic.com/generate_204
AUTO = url-test, policy-regex-filter=^(?!.*(YouTube|Россия|🇷🇺)).*, interval=600, timeout=5, url=http://www.gstatic.com/generate_204


[Rule]
RULE-SET,https://raw.githubusercontent.com/misha-tgshv/shadowrocket-configuration-file/main/rules/domains_community.list,PROXY
RULE-SET,https://raw.githubusercontent.com/misha-tgshv/shadowrocket-configuration-file/refs/heads/main/rules/domain_ips.list,PROXY,no-resolve
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Shadowrocket/Telegram/Telegram.list,PROXY
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Shadowrocket/Discord/Discord.list,PROXY
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Whatsapp/Whatsapp.list,PROXY
RULE-SET,https://raw.githubusercontent.com/fragilebees/whitelist/refs/heads/main/youtube.list,PROXY
RULE-SET,https://github.com/toneywhitez/zkeen_rules/releases/latest/download/telegram_ips.list,PROXY,no-resolve
RULE-SET,https://github.com/toneywhitez/zkeen_rules/releases/latest/download/meta_ips.list,PROXY,no-resolve
FINAL,DIRECT
